server {
    listen 89;
    server_name frontrunner;
    location / {
      # This would be the directory where your Vue app's static files are stored at
      root /usr/share/nginx/html;
      try_files $uri /index.html;
    }
   }