spring:
  application:
    name: ms-geo
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://ms-postgres:5432/geo_db"
    username: "postgres"
    password: "postgres"
    hikari:
      schema: "location"
  liquibase:
    default-schema: "location"
    change-log: "classpath:db.changelog/changelog-master.xml"
    drop-first: true

server:
  port: 8087

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    web: INFO

location:
  geo:
    data: "./countries.json"
