services:

  mc_postgres:
    image: "postgres:15"
    container_name: "mc_postgres"
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_USER=group_56"
      - "POSTGRES_PASSWORD=network"
      - "POSTGRES_DB=social"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - social

  mc_eureka:
    image: "nikolaykarpov/mc_eureka:1.0"
    container_name: "mc_eureka"
    ports:
      - 8761:8761
    networks:
      - social

  mc_dialogs:
    image: "nikolaykarpov/mc_dialogs:1.0"
    container_name: "mc_dialogs"
    ports:
      - 8077:8077
    depends_on:
      mc_eureka:
        condition: service_started
      mc_postgres:
        condition: service_started
    networks:
      - social

  mc_gateway:
    image: "nikolaykarpov/mc_gateway:1.0"
    container_name: "mc_gateway"
    ports:
      - 8765:8765
    depends_on:
      mc_eureka:
        condition: service_started
    networks:
      - social

networks:
  social:
    driver: bridge