server:
  port: 8765

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: gateway

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      enabled: true
      server:
        webmvc:
          routes:
            - id: MS-DIALOGS
              uri: http://localhost:8077
              predicates:
                - Path=/api/v1/dialogs/**

            - id: MS-ACCOUNT
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/account/**

            - id: MS-AUTH
              uri: http://localhost:8080
              predicates:
                - Path=/api/v1/auth/**

            - id: MS-GEO
              uri: http://localhost:8087
              predicates:
                - Path=/api/v1/geo/**

            - id: MS-POST
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/post/**

            - id: MS-FRIENDS
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/friends/**

            - id: MS-NOTIFICATIONS
              uri: http://localhost:8089
              predicates:
                - Path=/api/v1/notifications/**

            - id: MS-STORAGE
              uri: http://localhost:8097
              predicates:
                - Path=/api/v1/storage/**

logging:
  level:
    web: TRACE

#sending:
#  message:
#    dialogs:
#      path: "http://ms-dialogs:8077/api/v1/dialogs/sending/message"