CREATE SCHEMA IF NOT EXISTS location;

CREATE TABLE IF NOT EXISTS location.cities
(
id SERIAL PRIMARY KEY,
city_id UUID NOT NULL,
is_deleted BOOLEAN DEFAULT FALSE,
city_title VARCHAR(85) NOT NULL,
country_id UUID NOT NULL,
country_title VARCHAR(85) NOT NULL
);

CREATE TABLE IF NOT EXISTS location.countries
(
id SERIAL PRIMARY KEY,
country_id UUID NOT NULL,
is_deleted BOOLEAN DEFAULT FALSE,
country_title VARCHAR(85) NOT NULL
);